services:
  api:
    build: .
    container_name: sandy_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uvicorn dispatcher:app --host 0.0.0.0 --port 8000 --reload
